 version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: sh -c "npm i && npm run start:dev"
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      #- /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    restart: always



  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: shorty
      POSTGRES_DB: shorty
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

